const activities=[['✓','teal','Contrato PI 2026/0841 aprovado','Marina Santos aprovou o contrato de Grupo Horizonte','há 12 min'],['↗','blue','Contrato PI 2026/0838 enviado','Lançamento concluído no sistema demonstrativo','há 28 min'],['!','orange','Campo requer atenção','CNPJ divergente no contrato PI 2026/0836','há 42 min'],['＋','violet','Novo documento recebido','Contrato PI 2026/0847 pronto para conferência','há 1 h']];
const contracts=[['PI 2026/0841','Grupo Horizonte','Nova Mídia Comunicação','24/09/2026','Marina Santos','Enviado','Lançado há 12 min','sent'],['PI 2026/0842','Mercado Bom Dia','Agência Norte','24/09/2026','Carlos Lima','Em conferência','Aguardando revisão','review-status'],['PI 2026/0838','Rede Solar','Mosaico Mídia','23/09/2026','Marina Santos','Enviado','Lançado ontem','sent'],['PI 2026/0836','Techvale S.A.','Ponto Alto','23/09/2026','Ana Souza','Com erro','CNPJ divergente','error-status'],['PI 2026/0831','Instituto Horizonte','Nova Mídia Comunicação','22/09/2026','Carlos Lima','Enviado','Lançado há 2 dias','sent']];
const fields=[['Número do contrato / PI','PI 2026/0847','99%'],['Agência','Nova Mídia Comunicação','98%'],['Cliente / anunciante','Instituto Horizonte','97%'],['CNPJ','12.345.678/0001-90','74%','warn','Confira o formato do CNPJ'],['Produto / campanha','Campanha Institucional 2026','95%'],['Emissora','TV Horizonte','99%'],['Data inicial','01/10/2026','98%'],['Data final','31/10/2026','98%'],['Programa / faixa','Jornal da Manhã','93%'],['Quantidade de inserções','24','96%'],['Duração do material','30 segundos','94%'],['Valor unitário','R$ 1.250,00','89%'],['Valor bruto','R$ 30.000,00','91%'],['Desconto','10%','83%','warn','Confirme o percentual aplicado'],['Comissão','20%','95%'],['Valor líquido','R$ 21.600,00','91%']];
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
function renderActivities(){ $('#activity-list').innerHTML=activities.map(a=>`<div class="activity"><span class="activity-dot ${a[1]}">${a[0]}</span><div class="activity-text"><strong>${a[2]}</strong><small>${a[3]}</small></div><span class="activity-time">${a[4]}</span></div>`).join('') }
function renderFields(){ $('#field-grid').innerHTML=fields.map(f=>`<div class="field ${f[3]||''}"><label>${f[0]}</label><input value="${f[1]}" aria-label="${f[0]}"/><i class="field-status"></i>${f[3]?`<small>⚠ ${f[4]}</small>`:''}</div>`).join('') }
function renderHistory(){ $('#history-body').innerHTML=contracts.map(c=>`<tr><td><strong>${c[0]}</strong></td><td><strong>${c[1]}</strong><span class="table-muted">${c[2]}</span></td><td>${c[3]}</td><td>${c[4]}</td><td><span class="table-status ${c[7]}">${c[5]}</span></td><td>${c[6]}</td><td>⋮</td></tr>`).join('') }
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function showView(id){$$('.view').forEach(v=>v.classList.remove('active-view'));$('#'+id).classList.add('active-view');$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===id));const labels={dashboard:'Visão geral',new:'Novo contrato',history:'Histórico de contratos',reports:'Relatórios',processing:'Processamento',review:'Conferência'};$('#page-label').textContent=labels[id]||'Visão geral';window.scrollTo(0,0)}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
$('#camera-btn').onclick=()=>{toast('Câmera pronta. No celular, a câmera traseira será priorizada.');$('#file-input').click()};$('#images-btn').onclick=()=>$('#file-input').click();$('#pdf-btn').onclick=()=>$('#file-input').click();$('#dropzone').onclick=()=>$('#file-input').click();$('#dropzone').ondragover=e=>e.preventDefault();$('#file-input').onchange=()=>{if($('#file-input').files.length) startProcessing()};
function startProcessing(){showView('processing');let bar=$('#progress-bar'),p=67;const timer=setInterval(()=>{p+=11;bar.style.width=Math.min(p,100)+'%';if(p>=100){clearInterval(timer);setTimeout(()=>{showView('review');toast('Documento processado. Confira os campos destacados.');},450)}},430)}
$('#approve-btn').onclick=()=>{toast('Contrato aprovado e registrado na auditoria.');setTimeout(()=>showView('history'),900)};$('#draft-btn').onclick=()=>toast('Rascunho salvo com segurança.');$('#correction-btn').onclick=()=>toast('Solicitação de correção registrada.');
$('#search').oninput=e=>{$$('#history-body tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(e.target.value.toLowerCase())?'':'none')};
$('#clear-filters').onclick=()=>{$$('#reports select').forEach(s=>s.selectedIndex=0);toast('Filtros limpos. Exibindo todos os contratos.')};$('#print-report').onclick=()=>{toast('Relatório preparado para download.');window.print()};$('#export-report').onclick=()=>toast('CSV de relatórios gerado no modo demonstração.');
renderActivities();renderFields();renderHistory();
