/* Organização interna da tela Carteira comercial. Mantém o pipeline existente na aba Oportunidades. */
(() => {
  const root = document.getElementById('commercial');
  if (!root || root.dataset.tabsReady) return;
  root.dataset.tabsReady = 'true';
  const clients = [
    { name: 'Mercado Aurora', branch: 'Varejo', owner: 'Plínio Ferreira', contracts: 4, contracted: 620000, billed: 410000, status: 'Ativo', next: 'Reunião de acompanhamento', potential: 260000, days: 12 },
    { name: 'Instituto Nova Era', branch: 'Educação', owner: 'Deisi Santos', contracts: 3, contracted: 480000, billed: 310000, status: 'Ativo', next: 'Enviar proposta de renovação', potential: 180000, days: 36 },
    { name: 'Grupo Vale Verde', branch: 'Serviços', owner: 'Edson Ruiz', contracts: 2, contracted: 320000, billed: 250000, status: 'Atenção', next: 'Validar saldo de faturamento', potential: 140000, days: 18 },
    { name: 'Loja Horizonte', branch: 'Comércio', owner: 'Helis Almeida', contracts: 2, contracted: 210000, billed: 150000, status: 'Em prospecção', next: 'Agendar diagnóstico comercial', potential: 210000, days: 47 }
  ];
  const money = value => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 }).format(value);
  const safe = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
  const heading = root.children[0];
  const note = root.children[1];
  const oldNodes = [...root.children].slice(2);
  const opportunityPanel = document.createElement('div'); opportunityPanel.className = 'commercial-tab-panel commercial-opportunities-panel'; opportunityPanel.hidden = true;
  oldNodes.forEach(node => opportunityPanel.append(node));
  const tabs = document.createElement('div'); tabs.className = 'commercial-tabs'; tabs.setAttribute('role', 'tablist'); tabs.innerHTML = '<button type="button" role="tab" aria-selected="true" class="active" data-commercial-tab="clients">Clientes</button><button type="button" role="tab" aria-selected="false" data-commercial-tab="opportunities">Oportunidades</button>';
  const clientPanel = document.createElement('section'); clientPanel.className = 'commercial-tab-panel commercial-clients-panel'; clientPanel.innerHTML = `<div class="clients-heading"><div><p class="eyebrow">DADOS ILUSTRATIVOS · DEMONSTRAÇÃO</p><h2>Clientes</h2><p class="muted">Acompanhe clientes, contratos, contatos e situação financeira.</p></div><div class="clients-actions"><button class="secondary" id="export-client-list">⇩ Exportar lista</button><button class="primary" id="new-client">＋ Novo cliente</button></div></div><div class="clients-note">DADOS ILUSTRATIVOS · Clientes, valores e contatos são fictícios nesta demonstração.</div><div class="client-kpis" id="client-kpis"></div><section class="panel client-list-panel"><div class="client-toolbar"><label>Buscar cliente, contato ou ramo<input id="client-search" type="search" placeholder="Ex.: Mercado Aurora" /></label><label>Status<select id="client-status"><option value="">Todos</option><option>Ativo</option><option>Atenção</option><option>Em prospecção</option></select></label><label>Ramo da empresa<select id="client-branch"><option value="">Todos</option><option>Varejo</option><option>Educação</option><option>Serviços</option><option>Comércio</option></select></label><label>Contato comercial<select id="client-owner"><option value="">Todos</option><option>Plínio Ferreira</option><option>Deisi Santos</option><option>Edson Ruiz</option><option>Helis Almeida</option></select></label><button class="ghost" id="clear-client-filters">Limpar filtros</button></div><div class="client-table-wrap"><table class="client-table"><thead><tr><th>Cliente</th><th>Ramo</th><th>Contato responsável</th><th>Contratos ativos</th><th>Valor contratado</th><th>Valor faturado</th><th>Saldo a faturar</th><th>Status</th><th>Ações</th></tr></thead><tbody id="client-body"></tbody></table></div></section><section class="panel client-increments"><div><h2>Próximos incrementos</h2><p>Ideias preparadas para a próxima evolução da conta.</p></div><div class="increment-grid"><button data-client-suggestion="Segmentação por ramo">▦ <strong>Segmentação por ramo</strong><small>Visões por setor</small></button><button data-client-suggestion="Alertas de renovação">◷ <strong>Alertas de renovação</strong><small>Antecipar vencimentos</small></button><button data-client-suggestion="Histórico de interações">↺ <strong>Histórico de interações</strong><small>Registrar contatos</small></button><button data-client-suggestion="Pontuação do cliente">★ <strong>Pontuação do cliente</strong><small>Saúde da conta</small></button><button data-client-suggestion="Importar clientes">⇧ <strong>Importar clientes</strong><small>Preparar carga futura</small></button></div></section></section>`;
  root.append(opportunityPanel); root.insertBefore(tabs, opportunityPanel); root.insertBefore(clientPanel, opportunityPanel);
  heading.querySelector('h1').textContent = 'Clientes'; heading.querySelector('.muted').textContent = 'Acompanhe clientes, contratos, contatos e situação financeira.'; heading.querySelector('#new-opportunity').hidden = true;
  const detail = document.createElement('dialog'); detail.className = 'client-detail-dialog'; detail.id = 'client-detail-dialog'; root.append(detail);
  const filtered = () => { const search = document.getElementById('client-search').value.trim().toLocaleLowerCase('pt-BR'); const status = document.getElementById('client-status').value; const branch = document.getElementById('client-branch').value; const owner = document.getElementById('client-owner').value; return clients.filter(item => (!search || `${item.name} ${item.owner} ${item.branch}`.toLocaleLowerCase('pt-BR').includes(search)) && (!status || item.status === status) && (!branch || item.branch === branch) && (!owner || item.owner === owner)); };
  const renderClients = () => { const list = filtered(); document.getElementById('client-kpis').innerHTML = `<div><span>♙</span><strong>${clients.filter(x => x.status === 'Ativo').length}</strong><small>Clientes ativos</small></div><div><span>◎</span><strong>${clients.filter(x => x.status === 'Em prospecção').length}</strong><small>Em prospecção</small></div><div><span>▣</span><strong>${clients.reduce((sum, x) => sum + x.contracts, 0)}</strong><small>Contratos ativos</small></div><div><span>!</span><strong>${clients.filter(x => x.status === 'Atenção').length}</strong><small>Pendências financeiras</small></div>`; document.getElementById('client-body').innerHTML = list.length ? list.map(item => `<tr><td><strong>${safe(item.name)}</strong></td><td>${safe(item.branch)}</td><td>${safe(item.owner)}</td><td>${item.contracts}</td><td>${money(item.contracted)}</td><td>${money(item.billed)}</td><td>${money(item.contracted - item.billed)}</td><td><span class="client-status ${item.status === 'Ativo' ? 'active' : item.status === 'Atenção' ? 'attention' : 'prospecting'}">${safe(item.status)}</span></td><td><button class="client-details-button" data-client-details="${safe(item.name)}">Ver detalhes</button></td></tr>`).join('') : '<tr><td colspan="9" class="client-empty">Nenhum cliente encontrado para os filtros.</td></tr>'; };
  const showDetail = name => { const item = clients.find(client => client.name === name); if (!item) return; detail.innerHTML = `<form method="dialog"><div class="detail-head"><div><p class="eyebrow">CONTA · DADOS ILUSTRATIVOS</p><h2>${safe(item.name)}</h2><p>${safe(item.branch)} · <span class="client-status ${item.status === 'Ativo' ? 'active' : 'attention'}">${safe(item.status)}</span></p></div><button class="dialog-close" aria-label="Fechar">×</button></div><div class="detail-summary"><div><small>Contato responsável</small><strong>${safe(item.owner)}</strong></div><div><small>Próxima ação</small><strong>${safe(item.next)}</strong></div><div><small>Valor potencial</small><strong>${money(item.potential)}</strong></div><div><small>Total contratado</small><strong>${money(item.contracted)}</strong></div><div><small>Total faturado</small><strong>${money(item.billed)}</strong></div><div><small>Saldo a faturar</small><strong>${money(item.contracted - item.billed)}</strong></div></div><div class="detail-tabs"><button type="button" class="active">Visão geral</button><button type="button">Oportunidades</button><button type="button">Contratos</button><button type="button">Faturamento</button><button type="button">Histórico</button></div><div class="detail-timeline"><h3>Histórico demonstrativo</h3><div><b>Hoje</b><p>Contato comercial atualizou a próxima ação da conta.</p></div><div><b>12 dias atrás</b><p>Faturamento parcial registrado para o contrato demonstrativo.</p></div><div><b>30 dias atrás</b><p>Interação comercial registrada com o cliente.</p></div></div><div class="detail-actions"><button type="button" class="secondary" data-detail-action="Abrir conta">Abrir conta</button><button type="button" class="secondary" data-detail-action="Novo contrato">Novo contrato</button><button type="button" class="primary" data-detail-action="Registrar interação">Registrar interação</button></div></form>`; detail.showModal(); detail.querySelectorAll('.detail-tabs button').forEach(button => button.addEventListener('click', () => { detail.querySelectorAll('.detail-tabs button').forEach(tab => tab.classList.remove('active')); button.classList.add('active'); notify(`Aba ${button.textContent} selecionada na demonstração.`); })); detail.querySelectorAll('[data-detail-action]').forEach(button => button.addEventListener('click', () => notify(`${button.dataset.detailAction} preparado para ${item.name}.`))); };
  const notify = message => typeof toast === 'function' && toast(message);
  const setTab = tab => { const clientsActive = tab === 'clients'; clientPanel.hidden = !clientsActive; opportunityPanel.hidden = clientsActive; tabs.querySelectorAll('[data-commercial-tab]').forEach(button => { const active = button.dataset.commercialTab === tab; button.classList.toggle('active', active); button.setAttribute('aria-selected', String(active)); }); heading.querySelector('h1').textContent = clientsActive ? 'Clientes' : 'Carteira comercial e pendências'; heading.querySelector('.muted').textContent = clientsActive ? 'Acompanhe clientes, contratos, contatos e situação financeira.' : 'Acompanhe oportunidades antes do contrato e situações que exigem ação no faturamento.'; heading.querySelector('#new-opportunity').hidden = clientsActive; };
  tabs.addEventListener('click', event => { const button = event.target.closest('[data-commercial-tab]'); if (button) setTab(button.dataset.commercialTab); });
  root.addEventListener('click', event => { const details = event.target.closest('[data-client-details]'); if (details) showDetail(details.dataset.clientDetails); const suggestion = event.target.closest('[data-client-suggestion]'); if (suggestion) notify(`${suggestion.dataset.clientSuggestion} marcado como próximo incremento demonstrativo.`); if (event.target.closest('#new-client')) notify('Cadastro de novo cliente preparado para a próxima etapa.'); if (event.target.closest('#export-client-list')) { const csv = 'Cliente;Ramo;Contato;Contratado;Faturado;Saldo\n' + clients.map(x => `${x.name};${x.branch};${x.owner};${x.contracted};${x.billed};${x.contracted - x.billed}`).join('\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); a.download = 'clientes_demonstrativos.csv'; a.click(); notify('Lista demonstrativa exportada.'); } });
  ['client-search', 'client-status', 'client-branch', 'client-owner'].forEach(id => document.getElementById(id).addEventListener(id === 'client-search' ? 'input' : 'change', renderClients));
  document.getElementById('clear-client-filters').addEventListener('click', () => { ['client-status', 'client-branch', 'client-owner'].forEach(id => { document.getElementById(id).value = ''; }); document.getElementById('client-search').value = ''; renderClients(); });
  renderClients(); setTab('clients');
})();
